title: Xujia Li's Homepage
page-top-title: Xujia Li
top-section-bg-text: Data Science and Analysis
home-subtitle: Xujia LI&ensp;|&ensp;李绪嘉
copyright-text: '&copy; Xujia Li 2026. All Rights Reserved.'
